### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by ianlini** [ntucllab/striatum#13]
run CircleCI or whatever CI
- [ ] pylint
- [x] coverage
- [x] unit test
- [ ] installation test (both `requirements.txt` and `setup.py` should provide correct dependencies)

**Comment by stegben** [comment]
Jenkins, TravisCI, CircleCI

**Comment by ianlini** [comment]
(updated some action items) 
@taweihuang should try to use pylint on your local machine and editor first.

**Comment by ianlini** [comment]
I've enabled CircleCI
