### ISSUE TITLE
0.0.1

### ISSUE THREAD

**Issue by ianlini** [ntucllab/striatum#23]
Because we want to publish on pypi, we need to release (tag) a version ASAP. 
@stegben @taweihuang Please provide the changelog of the current master, note that this changelog is for the users of this package, not developers.
For example,

### New
- implement LinUCB ( #10 )
- implement UCB1 ( #10 )
- implement EXP3 ( #10 )
- implement EXP4P ( #10 )
- implement Thompson Sampling for Contextual Bandits with Linear Payoffs ( #10 )
- provide unit test for each bandit algorithm  ( #10 )
- simulation on fake data ( #10 )
- benchmark using movielens ( #29 )

I will update this list after your response.

**Comment by stegben** [comment]
Since it's the first version, maybe we only need one section 'New' to describe the functionality of this package?

more news:
* implement EXP4P
* implement LinThompson
* provide simulation on fake data

**Comment by taweihuang** [comment]
**New**

- implement LinUCB ( #10 )

- implement UCB1 ( #10 )

- implement EXP3 ( #10 )

- implement EXP4P ( #10 )

- implement LinThompSamp ( #10 )

- provide unit test for each bandit algorithm  ( #10 )

- simulation on fake data ( #10 )

**Comment by ianlini** [comment]
I don't think LinThompSamp is an algorithm. 
Why do we have this name?

**Comment by taweihuang** [comment]
The full name is Thompson Sampling for Contextual Bandits with Linear Payoffs.

**Comment by ianlini** [comment]
released and published on pypi, though the dependency is not correctly set XD
