### ISSUE TITLE
last_history_id should be generated by HistoryStorage

### ISSUE THREAD

**Issue by stegben** [ntucllab/striatum#25]
For scalability and maintainability, I think it's better generate the next history_id by calling ```add_history``` rather than controlled within models

**Comment by ianlini** [comment]
It's not for scalability or maintainability. 
If you don't get that id from HistoryStorage, it's a bug.

**Comment by ianlini** [comment]
We should add an property in HistoryStorage interface for getting that id

**Comment by ianlini** [comment]
I've read the LinUCB code. 
I don't think the `last_history_id` property is needed. 
We only need to return the `history_id` in `add_history()`. 
Can you tell us why we need that?
