### ISSUE TITLE
Functional API 

### ISSUE THREAD

**Issue by stegben** [ntucllab/striatum#28]
While implementing the bandit-server, I find it convenient to have pure function api. For example:
```python
def get_action(model_storage, context):
    ...

def reward(model_storage, history_storage, history_id, reward):
    ...
```
These are functions without side effect, thus can be used in a serverless structure. The model storage and history storage could be placed in one single source of true, which is the database. Once we call these API, we extract model and history storage through another interface, then put them into these functions.

**Comment by ianlini** [comment]
OOP is currently the most readable method. 
It exists not simply because it can have side effect, and functional programming exists not simply because it doesn't have side effect.
Be careful when you are using some concept you are not familiar to replace another concept you are also not familiar.
