### ISSUE TITLE
multiple action

### ISSUE THREAD

**Issue by ianlini** [ntucllab/striatum#32]
Can we support multiple action for a round? 
For example, user may want to get 5 possible response from the chatbot, and then choose one or many to be the answer. 
Please survey this.
Thanks.

**Comment by taweihuang** [comment]
I think it's okay. For example, linucb currently returns the action with the largest ucb, but actually it will calculate all ucbs of actions.

Maybe we can add an input `k` for `get_action` method, which represents the number of actions the user want to get. Then, we return  the first _k_ actions with larger ucbs.

Do you think it's okay?

**Comment by ianlini** [comment]
How about the reward? 
Can we reward multiple actions? 
Is it theorem guaranteed?

**Comment by ianlini** [comment]
If the user choose one to be the answer, then we should give reward 1 to that one, and 0 to others?

**Comment by taweihuang** [comment]
> How about the reward? 
> Can we reward multiple actions? 
> Is it theorem guaranteed?

My proposed method is a very naive approach, so definitely no theorem. and do not allow multiple reward XD 

> If the user choose one to be the answer, then we should give reward 1 to that one, and 0 to others?
It's the simplest way, but maybe we can try to design a pseudo reward mechanism. 

I'm not sure whether we'll face the multiple reward situations, but I currently find only one paper talking about CBMA problem (and it's from your lab XD) I'm thinking about using multi-output regression, but need some time to think about the problem.
http://www.csie.ntu.edu.tw/~htlin/paper/doc/taai13cbma.pdf

**Comment by ianlini** [comment]
You should reference the PR

**Comment by taweihuang** [comment]
Multiactions/linucb #37

**Comment by taweihuang** [comment]
Multiactions/linucb #37

**Comment by taweihuang** [comment]
#37
