### ISSUE TITLE
striatum 0.0.2

### ISSUE THREAD

**Issue by ianlini** [ntucllab/striatum#39]
I think we are ready to release the next version.
@taweihuang please provide the new/change/fix items.

**Comment by taweihuang** [comment]
## New

- allow multiple actions and reward in one history (#32)

## Change
- return [{'action': Action object, 'estimated_reward': float, 'score': float, 'uncertainty': float}] when using get_action

## Fix

- Fix bug in Exp4p

**Comment by ianlini** [comment]
You should reference the PR, and give more details of the bug 
"allow multiple actions and reward in one history" is a breaking change, not new

**Comment by taweihuang** [comment]
I've update the info. Please check it, thanks!

**Comment by ianlini** [comment]
What is @vectors?

**Comment by taweihuang** [comment]
Typo, sorry!
