### ISSUE TITLE
issues of the testing and setup

### ISSUE THREAD

**Issue by ianlini** [ntucllab/striatum#45]
1. python-tk and python3-tk system packages are required (these packages cannot be installed using pip)
2. numpy and scipy is required before installing

**Comment by yangarbiter** [comment]
1. which package requires python-tk?
2. Why is it a problem? we could mention them on readme

**Comment by ianlini** [comment]
1. matplotlib
2. not a problem, and striatum doesn't require matplotlib. Maybe we should add some notation for people who want to test the full functionality.

**Comment by ianlini** [comment]
sorry, my 2. is answering 1... 
2. not a problem, but we should mention it on readme

**Comment by ianlini** [comment]
We actually need tk-dev, not python-tk or python3-tk.
