### ISSUE TITLE
package structure

### ISSUE THREAD

**Issue by yangarbiter** [ntucllab/striatum#48]
https://github.com/ntucllab/striatum/pull/47#discussion-diff-77561298R7

Currently Action object is in striatum.bandit.bandit.Action.
Do we need to change Action from striatum.bandit.bandit.Action to striatum.bandit.Action,
or open a new submodule striatum.base.Action and also define all the interfaces there?

**Comment by ianlini** [comment]
How about striatum.action.Action?

**Comment by yangarbiter** [comment]
you mean start a new submodule action?
Why is it better than create a base submodule and put every abstract class in it?

**Comment by ianlini** [comment]
What's the advantage of "create a base submodule and put every abstract class in it"? 
I never thought that is useful, especially when the structure is complicated.

**Comment by ianlini** [comment]
closed because @yangarbiter didn't answer the questions
