### ISSUE TITLE
Inconsistancy in naming

### ISSUE THREAD

**Issue by yangarbiter** [ntucllab/striatum#49]
https://github.com/ntucllab/striatum/blob/master/striatum/bandit/bandit.py#L35
The attributes here have underline in the front

https://github.com/ntucllab/striatum/blob/master/striatum/bandit/bandit.py#L35
While others have them in the end

It seems underline in the front means protected members, though there is access
of these attributes in the test file. I think we should keep them in the end?

**Comment by ianlini** [comment]
The two links are the same. 
We should first think about whether we need to protect them.

**Comment by ianlini** [comment]
Only the generators in `Exp3` and `UCB1` use suffix `_`, but they will be removed after resolving #89
