### ISSUE TITLE
bad usage of BaseBandit.action_ids

### ISSUE THREAD

**Issue by ianlini** [ntucllab/striatum#52]
When BaseBandit.action_ids is used, the function will be called and generate a new list. 
This may cost too much, but the implementation is not considering that.

**Comment by ianlini** [comment]
My suggestion is making that function return a generator (change `[]` to `()`) and make sure we don't generate unnecessary list.

**Comment by yangarbiter** [comment]
@ianlini can you provide a reference to the source code?

**Comment by ianlini** [comment]
reference to what?

**Comment by yangarbiter** [comment]
https://github.com/ntucllab/striatum/blob/master/striatum/bandit/bandit.py#L73

**Comment by yangarbiter** [comment]
I think what we should do is maintain a `action_ids` list and update it whenever `add_action` is called

**Comment by ianlini** [comment]
That's an option, but we need to make sure that only few functions can change the actions, or it may be a bad design and can make lots of bugs.

**Comment by yangarbiter** [comment]
maybe we should make `_actions` read only?

**Comment by ianlini** [comment]
Let me first understand all the usage of `action_ids`, and then think which is better. 
I currently don't think there should be a list because the index of an action in the list is not fixed,
maybe the current usage is totally wrong.

**Comment by ianlini** [comment]
or maybe it's an wrong choice to use list to store the actions...

**Comment by ianlini** [comment]
`BaseBandit.action_ids` is replaced by `ActionStorage.iterids()`
