### ISSUE TITLE
what is action_id = int(action_id) in linucb?

### ISSUE THREAD

**Issue by ianlini** [ntucllab/striatum#59]
https://github.com/ntucllab/striatum/blob/master/striatum/bandit/linucb.py#L132 
I don't know why `action_id = int(action_id)` exists here. 
Before @taweihuang answers, I'll remove it first.

**Comment by taweihuang** [comment]
I'm not sure whether we'll have a string type or int type action_id, so I write this line.

**Comment by ianlini** [comment]
OK. That's assume it's int.
