### ISSUE TITLE
action id should be generated inside our model, not passed in

### ISSUE THREAD

**Issue by ianlini** [ntucllab/striatum#61]
This is a big issue. 
It's very strange to give the model the action id in `__init__` or `add_action`. 
Maybe the `action_id` attribute in `Action` object should be optional, and we give it id after `__init__` or `add_action` is called.

**Comment by taweihuang** [comment]
I think @stegben  may use  `action_id` to  map recommended actions to their relevant information stored in the database, so I think we should let the user input `action_id` himself to make sure the consistency of `action_id`.

**Comment by ianlini** [comment]
Yeah. We can still provide this function so that user can assign their ids. 
TODO:
- [ ] check the id to avoid conflict
- [ ] auto generate the action id if not provided
