### ISSUE TITLE
weights in Exp4.P are incorrect

### ISSUE THREAD

**Issue by ianlini** [ntucllab/striatum#66]
https://github.com/ntucllab/striatum/blob/master/striatum/bandit/exp4p.py#L90 
I found that in the second round (the model has been rewarded), w will be something like this: 
`{0: array([ 2.36154256,  2.03240672,  2.00984322,  2.01720784,  2.220576  ]), 1: array([ 2.36064009,  2.03172242,  2.00917387,  2.01653361,  2.21976697])}` 
which I think it's not the same as the original algorithm (every expert has only one weight value). 
This doesn't generate error because the `np.sum` here:
https://github.com/ntucllab/striatum/blob/master/striatum/bandit/exp4p.py#L98
incidentally sum all the value, so there won't be any array with wrong dimension. 
Is this a bug? I will update this issue after reading the reward part. Maybe I can find the answer myself.

**Comment by ianlini** [comment]
I think the problem is here:
https://github.com/ntucllab/striatum/blob/master/striatum/bandit/exp4p.py#L191
should be `context[i][k] / query_vector[k]`

**Comment by ianlini** [comment]
https://github.com/ntucllab/striatum/blob/master/striatum/bandit/exp4p.py#L193
this line is also incorrect...

**Comment by ianlini** [comment]
https://github.com/ntucllab/striatum/blob/master/striatum/bandit/exp4p.py#L195
this line is also incorrect (wrong T and K)

**Comment by taweihuang** [comment]
Yeah, you are correct. It's a bug giving wrong query_vector.
